baseURL = 'https://blog.blidir.fun/'
languageCode = 'en-US'
title = 'Logs and Learnings'

[module]
  [[module.imports]]
    path = "github.com/math-queiroz/rusty-typewriter"

[author]
  name = "Made Agus"
  email = "imade.agusdirawan@gmail.com"
  [author.social]
    github = "BliDir"

[rusty_typewriter]
  [params.rtwt]
    sidePane = false