baseURL = 'https://blog.blidir.fun/'
languageCode = 'en-US'
title = 'Logs and Learnings'
theme = "rusty-typewriter"

[rusty_typewriter]
 [params.rtwt]
  sidePane = false
  countPageItems = 7 
  searchPath = 'search'
 [params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5
 [params.rtwt.side.home]
  sidePaneSticky = false 
  taxonomies = ['tags']
  countTaxonomy = 6
 [params.rtwt.side.list]
  sidePaneSticky = false
 [params.rtwt.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[related]
 includeNewer = true
 [[related.indices]]
  name = 'tags'
  weight = 100

[taxonomies]
 tag = 'tags'

[params]
 summaryLength = 1

[params.links]
 hugo = 'https://gohugo.io/'
 theme = 'https://github.com/math-queiroz/rusty-typewriter'

[[menus.main]]
 name = 'Posts'
 pageRef = '/posts'
 weight = 1

[module]
 [module.hugoVersion]
  extended = false
  min = "0.116.0"