baseURL = 'https://blog.blidir.fun/'
languageCode = 'en-US'
title = 'Logs and Learnings'

[module]
  [[module.imports]]
    path = "github.com/math-queiroz/rusty-typewriter"

[rusty_typewriter]
  [params.rtwt]
    sidePane = false
    countPageItems = 7 
    searchPath = 'search'